GET http://localhost:9001/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjgwNzc3Mzk4fQ.vUEku0U6ZsqnB-Kus9U0zOpCeXi6gB7pbujq8qZk3iU

###

GET http://localhost:9001/books/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjgwNzc3Mzk4fQ.vUEku0U6ZsqnB-Kus9U0zOpCeXi6gB7pbujq8qZk3iU

###

GET http://localhost:9001/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjgwNzc3Mzk4fQ.vUEku0U6ZsqnB-Kus9U0zOpCeXi6gB7pbujq8qZk3iU


###

POST http://localhost:9001/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:9001/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}